name: Deploy on server

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: |
          echo "Deploy run"
          echo ${{ vars.TEST_ENV }}