name: Deployment on Develop

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: deploy
        run: |
          echo "Image: ${{ vars.IMAGE_NAME }}:${{ vars.IMAGE_TAG }}"