name: Deploy on server

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ vars.ENVIRONMENT_STAGE }}
    steps:
      - name: deploy
        run: |
          echo "Deploy run and say:"
          echo ${{ vars.TEST_ENV }}